name: openfold2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.13
  - cuda=12.9
  - pytorch=2.8
  - openmm
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - scipy
  - PyYAML
  - wandb
  - modelcif
  - ml-collections
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2